my_string = input("Введите ваше имя ")
print("Здравствуйте,", my_string)
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string[0])
print(my_string[-1])
print('Привет, я строка, пока'.replace(' ','#'))
